### ISSUE TITLE
[Bug] Erreur sur le format de date lors de la création d'un assessment (GraphQL Validation Failed)

### ISSUE THREAD

**Issue by vvandenschrieck** [TLCA-project/tlca-frontend#9]
Version : develop - commit [5058bb0](https://github.com/TLCA-project/tlca-frontend/commit/5058bb0d70dec6ddd58206f603cfdf7f74d2fd24)

Lorsqu'on crée un assessment dans l'espace manage (qu'on spécifie des dates ou non), la création échoue avec l'affichage du message "erreur" : 
<img width="1219" alt="Capture d’écran 2022-08-12 à 11 01 23" src="https://user-images.githubusercontent.com/1985444/184321938-2336abe8-3d61-4903-b701-040d8b825e75.png">

La réponse GraphQL renvoyée : 
`{
    "errors": [
        {
            "message": "Variable \"$end\" of type \"Date\" used in position expecting type \"DateTime\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$end\" of type \"Date\" used in position expecting type \"DateTime\".",
                        "    at Object.leave (/tlca-backend/node_modules/graphql/validation/rules/VariablesInAllowedPositionRule.js:64:17)",
                        "    at Object.leave (/tlca-backend/node_modules/graphql/language/visitor.js:324:32)",
                        "    at Object.leave (/tlca-backend/node_modules/graphql/utilities/TypeInfo.js:411:21)",
                        "    at visit (/tlca-backend/node_modules/graphql/language/visitor.js:197:21)",
                        "    at validate (/tlca-backend/node_modules/graphql/validation/validate.js:91:24)",
                        "    at validate (/tlca-backend/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/tlca-backend/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/tlca-backend/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        },
        {
            "message": "Variable \"$start\" of type \"Date\" used in position expecting type \"DateTime\".",
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Variable \"$start\" of type \"Date\" used in position expecting type \"DateTime\".",
                        "    at Object.leave (/tlca-backend/node_modules/graphql/validation/rules/VariablesInAllowedPositionRule.js:64:17)",
                        "    at Object.leave (/tlca-backend/node_modules/graphql/language/visitor.js:324:32)",
                        "    at Object.leave (/tlca-backend/node_modules/graphql/utilities/TypeInfo.js:411:21)",
                        "    at visit (/tlca-backend/node_modules/graphql/language/visitor.js:197:21)",
                        "    at validate (/tlca-backend/node_modules/graphql/validation/validate.js:91:24)",
                        "    at validate (/tlca-backend/node_modules/apollo-server-core/dist/requestPipeline.js:186:39)",
                        "    at processGraphQLRequest (/tlca-backend/node_modules/apollo-server-core/dist/requestPipeline.js:98:34)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                        "    at async processHTTPRequest (/tlca-backend/node_modules/apollo-server-core/dist/runHttpQuery.js:220:30)"
                    ]
                }
            }
        }
    ]
}`

**Comment by combefis** [comment]
Merci @vvandenschrieck  !

Le problème a été identifié, le type pour les champs "start" et "end" dans la requête pour récupérer l'"assessment" n'avait pas été modifié de "Date" à "DateTime" suite à un refactoring du backend.

Le bug a été corrigé par le commit 8f95cbd9d2324210bdab9d1253211b31976fc944 qui a été intégré dans le branche develop et également appliqué à la release 1.0 (v1.0.1).
